/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_des_stagaires;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ramzi
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    
    
    private DefaultTableModel dt;
    private int id;
    private String nom, prenom,sexe;
    private String service,mat;
    private String dure;
    
    private int i;
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    
    
    
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtrech = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtmat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtdure = new javax.swing.JTextField();
        comrech = new javax.swing.JComboBox<>();
        j1 = new javax.swing.JCheckBox();
        j3 = new javax.swing.JCheckBox();
        j2 = new javax.swing.JCheckBox();
        bActualiser = new javax.swing.JButton();
        bAjouter = new javax.swing.JButton();
        bRech = new javax.swing.JButton();
        bSupp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        combservice = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        bModifier = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();
        btnprecedent = new javax.swing.JButton();
        btnpremier = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 580));
        setPreferredSize(new java.awt.Dimension(950, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prenom");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sexe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Service");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Rechercher par :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        txtrech.setBackground(new java.awt.Color(102, 255, 102));
        txtrech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 100, -1));

        txtid.setBackground(new java.awt.Color(102, 255, 102));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));

        txtmat.setBackground(new java.awt.Color(102, 255, 102));
        txtmat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 100, -1));

        txtnom.setBackground(new java.awt.Color(102, 255, 102));
        txtnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, -1));

        txtprenom.setBackground(new java.awt.Color(102, 255, 102));
        txtprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, -1));

        txtdure.setBackground(new java.awt.Color(102, 255, 102));
        txtdure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtdure, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, -1));

        comrech.setBackground(new java.awt.Color(255, 255, 204));
        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "mat", "nom", "prenom", "service", "duree_de_stage", "sexe" }));
        comrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comrechActionPerformed(evt);
            }
        });
        getContentPane().add(comrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 100, -1));

        j1.setBackground(new java.awt.Color(255, 102, 102));
        j1.setText("Masculain");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        j3.setBackground(new java.awt.Color(255, 102, 102));
        j3.setText("Autre");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        j2.setBackground(new java.awt.Color(255, 102, 102));
        j2.setText("Féminin");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        bActualiser.setBackground(new java.awt.Color(255, 204, 0));
        bActualiser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_stagaires/actualiser .png"))); // NOI18N
        bActualiser.setText("Actualiser");
        bActualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bActualiserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bActualiserMouseExited(evt);
            }
        });
        bActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualiserActionPerformed(evt);
            }
        });
        getContentPane().add(bActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 150, -1));

        bAjouter.setBackground(new java.awt.Color(255, 204, 0));
        bAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_stagaires/ajouter.png"))); // NOI18N
        bAjouter.setText("Ajouter");
        bAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAjouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAjouterMouseExited(evt);
            }
        });
        bAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(bAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, -1));

        bRech.setBackground(new java.awt.Color(255, 153, 102));
        bRech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bRech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_stagaires/rechercher.png"))); // NOI18N
        bRech.setText("Rechercher");
        bRech.setActionCommand("Modifier");
        bRech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bRechMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bRechMouseExited(evt);
            }
        });
        bRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRechActionPerformed(evt);
            }
        });
        getContentPane().add(bRech, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 150, 40));

        bSupp.setBackground(new java.awt.Color(255, 204, 0));
        bSupp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_stagaires/supprimer.png"))); // NOI18N
        bSupp.setText("Supprimer");
        bSupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSuppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSuppMouseExited(evt);
            }
        });
        bSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuppActionPerformed(evt);
            }
        });
        getContentPane().add(bSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 460, 140, -1));

        jTable1.setBackground(new java.awt.Color(153, 255, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 220));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Duré de stage");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        combservice.setBackground(new java.awt.Color(255, 102, 102));
        combservice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "informatique", "gestion et recrutement", "maintenance", "logistique", "fiscale", "transport" }));
        getContentPane().add(combservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 100, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setText("jTextField1");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 100, -1));

        bModifier.setBackground(new java.awt.Color(255, 204, 0));
        bModifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_stagaires/modifier.png"))); // NOI18N
        bModifier.setText("Modifier");
        bModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bModifierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bModifierMouseExited(evt);
            }
        });
        bModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModifierActionPerformed(evt);
            }
        });
        getContentPane().add(bModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 150, 40));

        btndernier.setText("dernier");
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });
        getContentPane().add(btndernier, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        btnprecedent.setText("precedent");
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });
        getContentPane().add(btnprecedent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        btnpremier.setText("premier");
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });
        getContentPane().add(btnpremier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        btnsuivant.setText("suivant");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_des_stagaires/toph.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
      sexe=j1.getText();
    }//GEN-LAST:event_j1ActionPerformed

    private void bSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuppActionPerformed
        try{
        if(JOptionPane.showConfirmDialog(null, "attention est tu es sure que"
                + " tu veux supprimer ce stagaire","Supprimer stagaire",JOptionPane.YES_NO_OPTION)
                == JOptionPane.OK_OPTION){
   //si textfield id est vide ,on peux pas supprimmer
                st.executeUpdate("Delete from stagaire where id = "+ txtid.getText());
                Afficher(); // recharger la liste des stagiaires ...
           
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur supprimer stg !\n"+e.getMessage());
    }
    }//GEN-LAST:event_bSuppActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void comrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comrechActionPerformed

    private void bAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouterActionPerformed
     try{
   
String sql = "INSERT INTO stagaire  (mat,nom,prenom,service,duree_de_stage,sexe)VALUES (?,?,?,?,?,?)";
         PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1, txtmat.getText());
      ps.setString(2, txtnom.getText());
      ps.setString(3, txtprenom.getText());
      ps.setString(4, combservice.getSelectedItem().toString());
      ps.setString(5, txtdure.getText());
      ps.setString(6, sexe);
    
      
      ps.executeUpdate();
      Afficher(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "Stagiaire est ajouté");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur ajouter stg\n"+e.getMessage());
        System.err.println(""+e.getMessage());
    }

    }//GEN-LAST:event_bAjouterActionPerformed

    private void bAjouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAjouterMouseEntered
           bAjouter.setBackground(new java.awt.Color(122,22,223));
    }//GEN-LAST:event_bAjouterMouseEntered

    private void bAjouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAjouterMouseExited
        bAjouter.setBackground(new java.awt.Color(255,204,0)); 
        
    }//GEN-LAST:event_bAjouterMouseExited

    private void bModifierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModifierMouseEntered
         bModifier.setBackground(new java.awt.Color(122,22,223));
    }//GEN-LAST:event_bModifierMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
       
        try {
            // connexion à la base
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stg1","root","");
            st = con.createStatement();
            
            jrbg.add(j1);
            jrbg.add(j2);
            jrbg.add(j3);
            
            
            dt= new DefaultTableModel();
            
            dt.addColumn("id");
            dt.addColumn("mat");
            dt.addColumn("nom");
            dt.addColumn("prenom");
            dt.addColumn("service");
            dt.addColumn("duree");
            dt.addColumn("sexe");
            
            jTable1.setModel(dt);
            
            //afficher la liste des stagaires;
            
            Afficher();
           i=0;
            Deplacer(i);
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
       
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
        i = jTable1.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l utilisateur
         
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé stg\n"+e.getMessage());
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        sexe=j2.getText();
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
       sexe=j3.getText();
    }//GEN-LAST:event_j3ActionPerformed

    private void bModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModifierActionPerformed
        try{ 
        // message de confirmation !
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification sur un stagaire",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
           st.executeUpdate("UPDATE stagaire SET mat='"+txtid.getText()+"',nom='"+txtnom.getText()
      +"',prenom='"+txtprenom.getText()+"',service='"+combservice.getSelectedItem().toString()
                   +"',duree_de_stage='"+txtdure.getText()+"',sexe='"+sexe
                   +"' WHERE id = "+ txtid.getText());       
           //lorseque en fait +txtfield.gettext+ en doit ecrit les appostrophe ""
  
           Afficher(); // recharger la liste des stagiaires
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
    }
    }//GEN-LAST:event_bModifierActionPerformed

    private void bActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualiserActionPerformed
        actualiser();
        Afficher();
    }//GEN-LAST:event_bActualiserActionPerformed

    private void bRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRechActionPerformed
       try { 
    dt.setRowCount(0); //pour vider tableau 
    Statement st = con.createStatement();
        ResultSet rs = st.executeQuery( "SELECT * FROM stagaire WHERE "+combo()
                +"  like '%"+txtrech.getText()+"%'" );
    
     while( rs.next()) {
                
                id=rs.getInt("id");
                mat=rs.getString("mat");
                nom=rs.getString("nom");
                prenom=rs.getString("prenom");
                service=rs.getString("service");
                dure=rs.getString("duree_de_stage");
                sexe=rs.getString("sexe");
                Object[] t={id,mat,nom,prenom,service,dure,sexe};
                dt.addRow(t);
                
                
            }
     
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
            Afficher(); // afficehr tout les stgs
        }else{
            i = 0;
            Deplacer(i);
        }
    
}catch (Exception m){JOptionPane.showMessageDialog(null, ""+m.getMessage());
System.err.println(m);}
    }//GEN-LAST:event_bRechActionPerformed

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        try{
        i = 0;
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());}
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
       try{
        i--;
        Deplacer(i);
        // ou DeplacerStagiaire(--i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        try{
        i = dt.getRowCount() - 1 ; //
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
    }//GEN-LAST:event_btndernierActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
       try{
        i++;
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void bModifierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModifierMouseExited
        bModifier.setBackground(new java.awt.Color(255,204,0));
    }//GEN-LAST:event_bModifierMouseExited

    private void bSuppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSuppMouseEntered
        bSupp.setBackground(new java.awt.Color(122,22,223));
    }//GEN-LAST:event_bSuppMouseEntered

    private void bSuppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSuppMouseExited
        bSupp.setBackground(new java.awt.Color(255,204,0));
    }//GEN-LAST:event_bSuppMouseExited

    private void bActualiserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bActualiserMouseEntered
        bActualiser.setBackground(new java.awt.Color(122,22,223));
    }//GEN-LAST:event_bActualiserMouseEntered

    private void bActualiserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bActualiserMouseExited
        bActualiser.setBackground(new java.awt.Color(255,204,0));
    }//GEN-LAST:event_bActualiserMouseExited

    private void bRechMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRechMouseEntered
       bRech.setBackground(new java.awt.Color(122,22,223));
    }//GEN-LAST:event_bRechMouseEntered

    private void bRechMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRechMouseExited
       bRech.setBackground(new java.awt.Color(255,204,0));
    }//GEN-LAST:event_bRechMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualiser;
    private javax.swing.JButton bAjouter;
    private javax.swing.JButton bModifier;
    private javax.swing.JButton bRech;
    private javax.swing.JButton bSupp;
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JComboBox<String> combservice;
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JCheckBox j1;
    private javax.swing.JCheckBox j2;
    private javax.swing.JCheckBox j3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JTextField txtdure;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables

private void Afficher() {
    
    
        try {
            txtid.setEnabled(false);
            
            dt.setRowCount(0); //vider la la liste des stagaires
            
            rs= st.executeQuery("select * from stagaire");
            while( rs.next()) {
                
                id=rs.getInt("id");
                mat=rs.getString("mat");
                nom=rs.getString("nom");
                prenom=rs.getString("prenom");
                service=rs.getString("service");
                dure=rs.getString("duree_de_stage");
                sexe=rs.getString("sexe");
                Object[] t={id,mat,nom,prenom,service,dure,sexe};
                dt.addRow(t);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        

}

    private void Deplacer(int i) {
     try{
        if (dt.getRowCount() == 0){ //si il y aucun enregistrement tableau est vide
            btnprecedent.setEnabled(false);
            btnsuivant.setEnabled(false);
            actualiser();
        }else{
            if(i == 0){ //si i est localiser sur le premier enregistrement  
                btnprecedent.setEnabled(false);
                btnsuivant.setEnabled(true);
                }else if (i == dt.getRowCount()-1){ //  si i est localisé sur  dernier enregistrement
                btnprecedent.setEnabled(true);
            btnsuivant.setEnabled(false);
            }else{
                btnprecedent.setEnabled(true);
                btnsuivant.setEnabled(true);
            }
            if(dt.getRowCount() == 1){//si il y a un seul enregistrement, nous avons un seul ligne
                btnprecedent.setEnabled(false);
                btnsuivant.setEnabled(false);
            }
        }
        
        txtid.setText(dt.getValueAt(i, 0).toString()); 
        txtmat.setText(dt.getValueAt(i, 1).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        txtnom.setText(dt.getValueAt(i, 2).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
       txtprenom.setText(dt.getValueAt(i, 3).toString());
        combservice.setSelectedItem(dt.getValueAt(i, 4).toString());
        txtdure.setText(dt.getValueAt(i, 5).toString());
        String s = dt.getValueAt(i, 6).toString();
        if(s.equals("Masculain")){j1.setSelected(true);}else if(s.equals("Féminin")){j2.setSelected(true);}
        else {j3.setSelected(true);}
    }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
    }
    }


    public void actualiser(){ // fonction de type void ne retourne rien !!!!!!??
            txtid.setText("");
            txtnom.setText("");
            txtprenom.setText("");
            txtmat.setText("");
            combservice.setSelectedItem(1);
            j1.isSelected();
            txtdure.setText("");
}
    
    
    public String combo(){
switch(comrech.getSelectedIndex()){ 
        case 0: return "id"; 
        case 1: return "mat";
        case 2: return "nom";
        case 3: return "prenom";
        case 4: return "service";
        case 5: return "dure";
        case 6: return "sexe";
      }
      return "";
}
    
}
